### ISSUE TITLE
Add to the F-Droid store

### ISSUE THREAD

**Issue by rnauber** [Anuken/Mindustry#560]
Hi,
I like to ask, what you think about adding Mindustry to the F-Droid store (https://f-droid.org/) for free software. This should allow to reach even more people with this great, addictive game.

Bye,
Richard

**Comment by Anuken** [comment]
This is already planned [on the Trello.](https://trello.com/c/QwPVvcQ6/136-store-distribution)

**Comment by rnauber** [comment]
Oh, I missed that. So the milestone "v5+" means that it will probably take a while. Are you ok with me trying to submit a PR for inclusion to F-Droid in the meantime?

BTW, this is really a wonderful, well polished game, thanks for making it free software!

**Comment by Anuken** [comment]
I'm not very familiar with how F-Droid works, but glancing at their documentation, it seems like things are a bit more involved than just submitting a PR. Could you show me what you intend to do for submission?

**Comment by rnauber** [comment]
Well, i would follow "Proposal by Metadata Merge Request" from https://f-droid.org/en/docs/Inclusion_How-To/ . This boils down to provide a metadata file that instructs the build system build your app. My starting point is this (does not work yet):

**metadata/io.anuke.mindustry.yml in fdroiddata**
```
License: GPL-3.0-or-later
SourceCode: https://github.com/Anuken/Mindustry
IssueTracker: https://github.com/Anuken/Mindustry/issues

RepoType: git
Repo: https://github.com/Anuken/Mindustry

Builds:
  - versionName: v4Beta2
    versionCode: 82
    commit: v82
    subdir: android
    gradle:
      - yes

AutoUpdateMode: None
UpdateCheckMode: Tags

```

So I am currently setting up the build system locally and then I try to complete this.
